server:
    port: 8080
    servlet:
      context-path: /springboot-logging

### 配置本地环境数据源
spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
    mandatory-file-encoding: utf-8
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
logging:
  level:
    com:
      example:
            demo: debug
